on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: "Build on macos-latest"
    runs-on: macos-latest
    steps:
    - name: Initialize Java
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Initialize homebrew
      uses: Homebrew/actions/setup-homebrew@master
    - name: Install dependencies
      run: |
        brew install protobuf
        brew install swift-protobuf
    - name: Checkout root repository
      uses: actions/checkout@v2
      with:
        repository: sandpolis/sandpolis
    - name: Checkout submodules
      run: |
        git submodule update --init --remote --merge com.sandpolis.client.lockstone
        git submodule update --init --remote --merge plugin/com.sandpolis.plugin.desktop
    - name: Execute build
      run: |
        gradle --no-daemon :com.sandpolis.client.lockstone:build
